#!/bin/bash
#SBATCH -p gpu
#SBATCH --gres gpu:4
#SBATCH --ntasks=1
#SBATCH --job-name=MSMARCO_RETRIEVAL_DOCS
#SBATCH --time=8:00:00
#SBATCH --output=MSMARCO_RETRIEVAL_DOCS.out
#SBATCH -e Errors.err

#module purge
#module load 2021
#module load Miniconda3/4.9.2
eval "$(conda shell.bash hook)"
# Activate your environment
source activate colbert
# Run your code
echo starting the job
srun python /gpfs/home3/sgarcarz/PycharmProjects/ColBERT/retrieval.py
